import {EstadosBR} from './models/estados-br';

export const STATES: EstadosBR[] = [
  {value: 0, name:'Acre', uf:'AC'},
  {value: 1, name:'Alagoas', uf:'AL'},
  {value: 2, name:'Amapá', uf:'AP'},
  {value: 3, name:'Bahia', uf:'BA'},
  {value: 4, name:'Ceará', uf:'CE'},
  {value: 5, name:'Distrito Federal', uf:'DF'},
  {value: 6, name:'Espirito Santo', uf:'ES'},
  {value: 7, name:'Goiás', uf:'GO'},
  {value: 8, name:'Maranhão', uf:'MA'},
  {value: 9, name:'Mato Grosso', uf:'MT'},
  {value: 10, name:'Mato Grosso do Sul', uf:'MS'},
  {value: 11, name:'Minas Gerais', uf:'MG'},
  {value: 12, name:'Pará', uf:'PA'},
  {value: 13, name:'Paraíba', uf:'PB'},
  {value: 14, name:'Paraná', uf:'PR'},
  {value: 15, name:'Pernambuco', uf:'PE'},
  {value: 16, name:'Piauí', uf:'PI'},
  {value: 17, name:'Rio de Janeiro', uf:'RJ'},
  {value: 18, name:'Rio Grande do Sul', uf:'RN'},
  {value: 19, name:'Rio Grande do Norte', uf:'RS'},
  {value: 20, name:'Rondonia', uf:'RO'},
  {value: 21, name:'Roraima', uf:'RR'},
  {value: 22, name:'Santa Catarina', uf:'SA'},
  {value: 23, name:'Sergipe', uf:'SE'},
  {value: 24, name:'São Paulo', uf:'SP'},
  {value: 25, name:'Tocantins', uf:'TO'}
] 